
//CORPORATE DATA STRUCTURE
export const corporateCreditInformationRecord = {
    institution: "",
    tradingName: "",
    taxNo: "",
    vatNo: "",
    companyRegNo: "",
    companyRegistrationDate: "",
    companyCeaseDate: "",
    industry: "",
    postalAddressLine1: "",
    postalAddressLine2: "",
    postalCode: "",
    physicalAddressLine1: "",
    physicalAddressLine2: "",
    physicalAddressPostalCode: "",
    physicalAddressPlotNumber: "",
    physicalAddressProvince: "",
    physicalAddressDistrict: "",
    physicalAddressSector: "",
    physicalAddressCell: "",
    country: "",
    emailAddress: "",
    telephone1: "",
    telephone2: "",
    telephone3: "",
    telephone4: "",
    telephone5: "",
    telephone6: "",
    facsimile1: "",
    facsimile2: "",
    accountNumber: "",
    oldAccountNumber: "",
    accountType: "",
    accountStatus: "",
    classification: "",
    accountOwner: "",
    jointLoanParticipants: "",
    currencyType: "",
    dateAccountOpened: "",
    dateAccountUpdated: "",
    termsDuration: "",
    accountRepaymentTerm: "",
    openingBalance: "",
    currentBalance: "",
    availableCredit: "",
    currentBalanceIndicator: "",
    scheduledPaymentAmount: "",
    actualPaymentAmount: "",
    amountPastDue: "",
    installmentsInArrears: "",
    daysInArrears: "",
    dateClosed: "",
    lastPaymentDate: "",
    interestRateAtDisbursement: "",
    firstPaymentDate: "",
    nature: "",
    category: "",
    sectorOfActivity: "",
    approvalDate: "",
    finalPaymentDate: ""
};


//COLLATERAL DATA STRUCTURE

export const collateralInformationRecord = {
    accountNumber: "",
    collateralExpiryDate: "",
    collateralLastValuationDate: "",
    collateralValue: "",
    collateralType: "",
    collateral_Id: "",
}

//CONSUMER DATA STRUCTURE

export const consumerCreditInformationRecord = {
    salutation: "",
    surName: "",
    foreName1: "",
    foreName2: "",
    foreName3: "",
    nationalId: "",
    passportNumber: "",
    nationality: "",
    taxNumber: "",
    drivingLicenseNumber: "",
    socialSecurityNumber: "",
    healthInsuranceNumber: "",
    maritalStatus: "",
    noOfDependants: "",
    gender: "",
    dateOfBirth: "",
    placeOfBirth: "",
    postalAddressNumber: "",
    postalCode: "",
    physicalAddressLine1: "",
    physicalAddressLine2: "",
    physicalAddressPostalCode: "",
    physicalAddressPlotNumber: "",
    physicalAddressProvince: "",
    physicalAddressDistrict: "",
    physicalAddressSector: "",
    physicalAddressCell: "",
    country: "",
    emailAddress: "",
    residenceType: "",
    workTelephone: "",
    homeTelephone: "",
    mobileTelephone: "",
    facsimile: "",
    employerName: "",
    employerAddressLine1: "",
    employerAddressLine2: "",
    employerTown: "",
    employerCountry: "",
    occupation: "",
    income: "",
    incomeFrequency: "",
    groupName: "",
    groupNumber: "",
    accountNumber: "",
    oldAccountNumber: "",
    accountType: "",
    accountStatus: "",
    classification: "",
    accountOwner: "",
    numberOfJointLoanParticipants: "",
    currencyType: "",
    dateAccountOpened: "",
    dateAccountUpdated: "",
    termsDuration: "",
    accountRepaymentTerm: "",
    openingBalance: "",
    currentBalance: "",
    availableCredit: "",
    currentBalanceIndicator: "",
    scheduledPaymentAmount: "",
    actualPaymentAmount: "",
    amountPastDue: "",
    installmentsInArrears: "",
    daysInArrears: "",
    dateClosed: "",
    lastPaymentDate: "",
    interestRateAtDisbursement: "",
    firstPaymentDate: "",
    nature: "",
    category: "",
    sectorOfActivity: "",
    approvalDate: "",
    finalPaymentDate: ""
};
