
//CORPORATE DATA STRUCTURE
export const corporateInformationRecord = {
    institutionName: "",
    tradingName: "",
    taxNo: "",
    vatNo: "",
    companyRegNo: "",
    companyRegistrationDate: "",
    companyCeaseDate: "",
    industry: "",
    postalAddressLine1: "",
    postalAddressLine2: "",
    postalCode: "",
    physicalAddressLine1: "",
    physicalAddressLine2: "",
    physicalAddressPostalCode: "",
    physicalAddressPlotNumber: "",
    physicalAddressProvince: "",
    physicalAddressDistrict: "",
    physicalAddressSector: "",
    physicalAddressCell: "",
    country: "",
    emailAddress: "",
    telephone1: "",
    telephone2: "",
    telephone3: "",
    telephone4: "",
    telephone5: "",
    telephone6: "",
    facsimile1: "",
    facsimile2: "",
    accountNumber: "",
    oldAccountNumber: "",
    accountType: "",
    accountStatus: "",
    classification: "",
    accountOwner: "",
    jointLoanParticipants: "",
    currencyType: "",
    dateOpened: "",
    dateUpdated: "",
    termsDuration: "",
    repaymentTerm: "",
    openingBalanceCreditLimit: "",
    currentBalance: "",
    availableCredit: "",
    currentBalanceIndicator: "",
    scheduledMonthlyPaymentAmount: "",
    actualPaymentAmount: "",
    amountPastDue: "",
    installmentsInArrears: "",
    daysInArrears: "",
    dateClosed: "",
    lastPaymentDate: "",
    interestRate: "",
    firstPaymentDate: "",
    nature: "",
    category: "",
    sectorOfActivity: "",
    approvalDate: "",
    finalPaymentDate: ""
};


//COLLATERAL DATA STRUCTURE

export const collateralInformationRecord = {
    accountNumber: "",
    collateralExpiryDate: "",
    collateralLastValuationDate: "",
    collateralValue: "",
    collateralType: "",
    collateral_Id: "",
}